name: Security Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif
          soft_fail: true # Don't fail the build on Checkov issues, just report them#          # checkov_args: --check CKV_AZURE_99 --check CKV_AZURE_100 # Example of how to specify specific checks

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif
